apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-wml-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: Cloud Pak for Data Watson Machine Learning
  publisher: IBM
  sourceType: grpc
  # ibm-wml-cpd-4.0.5.tgz
  image: icr.io/cpopen/ibm-cpd-wml-operator-catalog@sha256:1efca82d32dfb89f515570e802af1e7b5a29a4e71f678bee374577f568866d96
  updateStrategy:
    registryPoll:
      interval: 45m