apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ws-runtimes-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: icr.io/cpopen/ibm-cpd-ws-runtimes-operator-catalog@sha256:14352ea4f71c1917cdeb860b64645fd56a3812ff69255b26dfb0c7199005e1a0
  imagePullPolicy: IfNotPresent
  displayName: CPD Watson Studio Runtimes
  publisher: IBM
  updateStrategy:
    registryPoll:
      interval: 45m