apiVersion: batch/v1
kind: Job
metadata:
  generateName: cpd-scheduling-presync-hook-
  namespace: ibm-common-services
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: job
          image: "quay.io/ibmgaragecloud/nodejs"
          imagePullPolicy: IfNotPresent
          command: ["bash"]
          args:
            - "c"
            - "while !  [ `oc get scheduling -n ibm-common-services -o jsonpath='{.items[0].status.cpd-schedulingStatus} {\"\n\"}'` = \"Completed\" ] > /dev/null; do sleep 30; done"
      restartPolicy: Never
  backoffLimit: 4