# Default values for ibm-cpd-platform-instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


ibmcpdplatforminstance:
  name: ibmcpd-cr
  spec:
    license:
      accept: true
      license: Enterprise
    storageClass: managed-nfs-storage
    zenCoreMetadbStorageClass: managed-nfs-storage
    version: "4.0.4"

argocd-hook-job:
  name: cpd-platform-presync
  namespace: ibm-common-services
  hook:
    enabled: true
    hooktype: PreSync
  hookdeletepolicy:
    enabled: true
    hookdeletepolicytype: HookSucceeded
  serviceaccount: cpd-instance-argocd-hook-job-sa
  roleaccess:
    - verbs:
        - get
        - list
      apiGroups:
        - "scheduler.spectrumcomputing.ibm.com"
      resources:
        - scheduling
  init:
    enabled: false
  container:
    image: "quay.io/ibmgaragecloud/helm-kubectl"
    tag: "3.2.3"
    command: "bash"
    args:
      - "-c"
      - "while !  [ `kubectl get scheduling -n ibm-common-services -o jsonpath='{.items[0].status.cpd-schedulingStatus}'` = \"Completed\" ] > /dev/null; do echo \"checking for Cloud Pak for Data Scheduler....\"; sleep 30; done; echo \"Scheduler is installed.\""

