ibm-cp4d-watson-studio-instance:
  metadata:
    name: ws-cr

  spec:
    docker_registry_prefix: cp.icr.io/cp/cpd
    license:
      accept: "true"
      license: Enterprise
    version: 4.0.1
    storageClass: managed-nfs-storage

argocd-hook-job:
  name: cpd-platform-presync
  namespace: cloudpak
  hook:
    enabled: true
    hooktype: PreSync
  hookdeletepolicy:
    enabled: true
    hookdeletepolicytype: HookSucceeded
  serviceaccount: cpd-instance-argocd-hook-job-sa
  roleaccess:
    - verbs:
        - get
        - list
      apiGroups:
        - "cpd.ibm.com"
      resources:
        - Ibmcpd
        - ibmcpds
  init:
    enabled: false
  container:
    image: "quay.io/ibmgaragecloud/helm-kubectl"
    tag: "3.2.3"
    command: "bash"
    args:
      - "-c"
      - "set -o xtrace; while !  [ `kubectl get Ibmcpd ibmcpd-cr -n cloudpak -o jsonpath='{.status.controlPlaneStatus}'` = \"Completed\" ] > /dev/null; do echo \"checking for Cloud Pak for Data Control Plane....\"; sleep 30; done; echo \"Control Plane is installed.\""

